POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "someusername_1",
    "password": "somepassword_1"
}

###

GET http://localhost:8080/users?name=user1
Authorization: f9g1wnbtvcu

###